name: h5coro
channels:
  - conda-forge
dependencies:
  - cmake
  - cxx-compiler
  - gdal
  - git
  - libcurl
  - lua=5.3
  - make
  - openssl
  - proj
  - pybind11
  - rapidjson
  - r-uuid 
  - unzip
  - vim
  - Zlib 
